version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: mambaforge-22.9

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - method: pip
      path: .
    - method: setuptools
      path: .

conda:
  environment: environment.yml
